#!/bin/sh

set -e

if [ ! -f /opt/homebrew/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -d ~/dotfiles ]; then
  cd ~
  git clone https://github.com/Earth-worm/dotfiles.git
fi
brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/.config ]; then
  cd ~
  mkdir ~/.config
fi

stow -v -d ~/dotfiles/packages -t ~ yabai starship fish karabiner nvim skhd

defaults write com.apple.desktopservices DSDontWriteNetworkStores True